# 1. 지연실행 defer

Go 언어의 defer 키워드는 특정 문장 혹은 함수를 나중에 (defer를 호출하는 함수가 리턴하기 직전에) 실행하게 한다. 
일반적으로 defer는 C#, Java 같은 언어에서의 **finally 블럭처럼 마지막에 Clean-up 작업을 위해 사용된다.** 
아래 예제는 파일을 Open 한 후 바로 파일을 Close하는 작업을 defer로 쓰고 있다. 
이는 차후 문장에서 어떤 에러가 발생하더라도 항상 파일을 Close할 수 있도록 한다.

```go
package main
 
import "os"
 
func main() {
    f, err := os.Open("1.txt")
    if err != nil {
        panic(err)
    }
 
    // main 마지막에 파일 close 실행
    defer f.Close()
 
    // 파일 읽기
    bytes := make([]byte, 1024)
    f.Read(bytes)
    println(len(bytes))
}
```

## defer의 실행 과정이 내 생각과 같지 않아서 알아보았다. 

아래 코드를 보자

```go
package main

import "fmt"

func main() {
	defer fmt.Println("world")
    fmt.Println("Hello")
}
```
"world"가 먼저 실행되고 "Hello"가 실행될거같은데 그렇지 않다. defer는 main()함수가 종료되기 직전인 마지막에 실행된다.

### 다시 알아본 이유

```go
func main() {
	client, err := ent.Open("mysql", "root:root@tcp(127.0.0.1:3306)/ent")
	if err != nil {
		log.Fatalf("failed opening connection to sqlite: %v", err)
	}
	defer client.Close()

	ctx := context.Background()

	if err := client.Schema.Create(context.Background()); err != nil {
		log.Fatalf("failed creating schema resources: %v", err)
	}

	fmt.Println(Gen(ctx, client))
}
```

golang에서 db를 사용해보려고 하는데 ```defer client.Close()```이 중간에 있음에도 불구하고 다음동작이 정상적으로 처리되길레 한번 확인해 본것이다... 며칠을 의아해 했다.ㅋ..ㅋ

# 2. panic

Go 내장함수인 panic()함수는 **현재 함수를 즉시 멈추고 현재 함수에 defer 함수들을 모두 실행한 후 즉시 리턴한다.** 
이러한 panic 모드 실행 방식은 다시 **상위함수에도 똑같이 적용**되고, 계속 **콜스택을 타고 올라가며 적용**된다. 
그리고 마지막에는 프로그램이 에러를 내고 종료하게 된다.

```go
package main
 
import "os"
 
func main() {
    // 잘못된 파일명을 넣음
    openFile("Invalid.txt")
     
    // openFile() 안에서 panic이 실행되면
    // 아래 println 문장은 실행 안됨
    println("Done") 
}
 
func openFile(fn string) {
    f, err := os.Open(fn)
    if err != nil {
        panic(err)
    }
 
    defer f.Close()
}
```

# 3. recover

Go 내장함수인 recover()함수는 panic 함수에 의한 **패닉상태를 다시 정상상태로 되돌리는 함수**이다. 
위의 panic 예제에서는 main 함수에서 println() 이 호출되지 못하고 프로그램이 crash 하지만, 아래와 예제와 같이 recover 함수를 사용하면 panic 상태를 제거하고 openFile()의 다음 문장인 println() 을 호출하게 된다.

```go
package main
 
import (
    "fmt"
    "os"
)
 
func main() {
    // 잘못된 파일명을 넣음
    openFile("Invalid.txt")
 
    // recover에 의해
    // 이 문장 실행됨
    println("Done") 
}
 
func openFile(fn string) {
    // defer 함수. panic 호출시 실행됨
    defer func() {
        if r := recover(); r != nil {
            fmt.Println("OPEN ERROR", r)
        }
    }()
 
    f, err := os.Open(fn)
    if err != nil {
        panic(err)
    }
 
    defer f.Close()
}
```